# Project information
site_name: DXRT SDK Documents
extra:
  version: v0.2
    #    provider: mike
  generator: false
  social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/deepx-ai
     - icon: fontawesome/brands/linkedin
       link: https://www.linkedin.com/company/deepx-corporation/
# Documentation and theme
use_directory_urls: false
docs_dir: docs
site_dir: html_docs
theme: 
  name : material
  language: en
  font:
    text: Noto Serif Korean
    code: Noto Sans Mono
  logo: ./img/deepx.png
  favicon: ./img/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
     - toc.integrate
     - content.code.annotate
     - navigation.tabs
     - navigation.tabs.sticky
nav:
  - Introduction: index.md
  - About DX-RT :
    - Introduction.md
    - Installation.md
    - Build.md
    - How-To-Create-CMake-Project.md
    - Getting-Started.md
    - Inference-Guide.md
    - Examples.md
    - High-Level-Design.md
    # - Low-Level-Design.md
    - API-Reference.md
    - Test.md
plugins:
  - search
  - mkdocs-video
#extra:
#  alternate:
#    - name: English
#      link: /en/    
#      lang: en
#    - name: Korean
#      link: /kr/
#      lang: kr
extra_css: 
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - def_list
  - toc:
        permalink: "true"
        baselevel: 1
        separator: ">_"
        toc_depth: 3
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: ⓒ Copyright 2022 <a href="http://deepx.ai">DEEPX</a>. All Rights Reserved.
