option(USE_ORT "Use ONNX Runtime" OFF)
option(USE_DXRT_TEST "Use DXRT Unit Test" ON)
if(MSVC)
	option(USE_SHARED_DXRT_LIB "Build for DXRT Shared Library" OFF)
else()
	option(USE_SHARED_DXRT_LIB "Build for DXRT Shared Library" ON)
endif()
option(USE_PYTHON "Use Python" ON)
option(ENABLE_DEBUG_INFO "Include debugging informations in build output" ON)
option(USE_SERVICE "Use DXRT Service" OFF)
